Directory Structure:

└── ./
    └── Symbolic Regression
        ├── dataset.csv
        └── hw1_symbolic_regression.py



---
File: /Symbolic Regression/dataset.csv
---

y,x_1,x_2
4.498100224141801,1.3699194175569727,0.46282684786010003
5.91391350451023,3.000167096643054,0.26611279893239
10.084819587218334,3.015507231183728,0.3226265757374635
3.8923139284999264,2.65789892333805,0.21251182479585254
12.76823762198122,2.9917022579579355,0.3883263952404367
0.16647494179306777,0.686736645651402,0.27067186733695214
250.11667269491574,3.783479134525188,1.3354540711195546
335.8576733880321,3.371600403889156,1.733960777246128
6.555272368711134,1.9829608679496626,0.4211276723226808
0.036176847352047514,0.20717051334089848,1.111937254921918
4.232894637496295,1.763430400086853,0.3723373272798342
7.778056654875659,3.2498400566010215,0.27014792023266987
33.06455893996589,1.474569669024098,1.2474582634943017
214.95783232455733,1.0682895020397345,4.37364762881306
1.5625720306315114,0.5298083941393881,0.7747264886876503
150.03655877683948,4.206514481763229,0.931108694765174
1.7959368079896634,1.3855844370853914,0.3021040819225207
8.013649625907547,2.4827427970722105,0.36697446524957944
2.6289381273252754,1.8081183765288331,0.2596196807697375
140.89143058316003,4.661909997632615,0.811691679461077
0.7884390684313327,0.10863299095429745,0.6902268154771776
3.578133216340387,0.668214591518258,0.9864131693987349
277.97987588781695,4.735454234140596,1.1239365272201909
32.929100579517836,4.997748917207221,0.37035302486476307
501.149920955207,3.843779023099884,1.858256269884075
6.371863063465601,3.199317979810525,0.24681706606084894
0.7012968239854119,0.15615677284458235,0.35308552493771
32.21093489363142,2.84463985098785,0.6346383329272075
278.9593423632745,4.471120422359804,1.1929415489778692
1.3193479011613696,1.484795135485279,0.242372661460303
9.952617295923673,2.086164716214701,0.4912390097985834
248.2371856845594,3.2853624055071475,1.534223471229243
10.153536801503598,3.990617734641,0.24892101813038348
6.8408731107098495,2.7358075437729714,0.3151274462022913
3.0633892460990446,2.4402980238656906,0.202193018356406
8.731651110898675,4.144657875303688,0.22331861986180507
61.30497610096724,3.221787957767079,0.7747125704302447
380.67130096693467,3.473673208069966,1.7929535833403774
-0.21323940738010924,0.6008179642838954,0.2531323176447164
27.02837456312003,3.0423331491516032,0.5450458167041549
2.497493889059562,2.582219092302789,0.2004034481431449
22.13994510258929,2.7816857875607104,0.5360657119057003
0.03486653283709279,0.13477917758798666,0.38323944438125074
2.1815593679608924,1.925387022644895,0.22297648367706052
-0.06662477475020603,0.4414370278752989,0.28216626110971943
0.3066500440650769,0.37765314928918103,0.7048092460661193
959.9570118671709,1.362398950914084,7.262215384859493
233.71714844393915,4.274714942006937,1.1409711671371272
1101.8946434310508,3.87637436732142,2.7338881968522277
5.673477067341869,2.774954021663627,0.2864508399598858



---
File: /Symbolic Regression/hw1_symbolic_regression.py
---

# -*- coding: utf-8 -*-
"""HW1_Symbolic_Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/benyaminmaleki/hw1-symbolic-regression.c051eb60-070c-4f8b-894a-6e298dca78d5.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250716/auto/storage/goog4_request%26X-Goog-Date%3D20250716T190635Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D6817a5b44551a1c6fb29fa84464594dc9d7dc0581dba9a9c54dfe7b69c876222a259e5fce15572d3d2189f1bbb759f81e698603eb356050cbe722c7644aca1da436076dfac4357ed8c10aae3d1f74ab98c1ca6992b2d04d44d7322618692858ef0d78d1a806fc4b0224cc08d2e1fe374688e4beb3a3ba2ff4b3d00a9115ac220caed7becb94dac7b03d4d2f7e67414e194894dbb1d7addab3806a4f4ac4f3638e7f0b5dc72bd59fe8edabd476e8b4d8839f10815030c72b6a68a099df96b05fab43c4855a0d6736d7eccc120095bb17ec49a42069df725078044bdd0a1f2026f013443060db1840c0d0634819c03897f465922c9b8233c0f33299715e7a7ed42

<br>
<font>
<div dir=ltr align=center>
<font color=0F5298 size=7>
    System 2 - Homework 1<br>
<font color=2565AE size=5>
    Spring 2025<br>
<font color=3C99D size=5>
    Symbolic Regression <br>

---

### Student Number = 99102286

### Full Name = Benyamin Maleki

---

# Introduction

This notebook explores two methods for performing symbolic regression, focusing on both traditional and modern AI-driven approaches:

## 1. EQL-Based Symbolic Regression  
The first approach we implement is based on **Equation Learner (EQL)**, a neural network-based symbolic regression technique. EQL leverages neural networks with activation functions that encourage the discovery of symbolic expressions, making it a differentiable and trainable approach for learning equations directly from data. This method helps in bridging the gap between deep learning and symbolic reasoning.

## 2. Seq2Seq-Based Symbolic Regression with Transformers
A more recent and powerful approach to symbolic regression leverages Sequence-to-Sequence (Seq2Seq) models using Transformers. In this method, we frame symbolic regression as a translation problem, where the input consists of numerical data points and the output is a corresponding mathematical expression. By training a Transformer model on pairs of input data and symbolic expressions, we can enable it to generalize and infer underlying symbolic patterns. This approach benefits from the self-attention mechanism, allowing it to capture long-range dependencies in mathematical structures effectively.

# Datasets

We use two datasets to evaluate our methods:

- **Dataset 1:** This dataset is provided in the notebook, and its underlying mathematical formula is explicitly given. It serves as a reference to assess the performance of different symbolic regression approaches. The expression we consider is: `2 * x + np.sin(x) + x * np.sin(x)`.
  
- **Dataset 2:** This dataset is also provided with the notebook, but its underlying mathematical relationship is hidden. Throughout different parts of the notebook, you will attempt to uncover the equation governing this dataset. Your responses will be evaluated based on how accurately you recover the true formula.

By working through both datasets, we aim to test the robustness and accuracy of various symbolic regression techniques while providing an engaging and exploratory learning experience.

# Import Libraries
"""

import pickle
import numpy as np
import sympy as sp
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from inspect import signature
import time
from tqdm.auto import tqdm
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import sympy
import glob
import time
import signal
import random
import warnings
import json
import re

warnings.filterwarnings('ignore')

"""# Generate Dataset"""

def generate_data(func, N, range_min=-2, range_max=2, noise_std=0.1):
    """
    Generates a dataset by evaluating the given function on random input values with added noise.

    Parameters:
    func (callable): A function that takes numerical inputs and returns a scalar output.
    N (int): The number of data points to generate.
    range_min (float, optional): The minimum value of the input range. Default is -2.
    range_max (float, optional): The maximum value of the input range. Default is 2.
    noise_std (float, optional): Standard deviation of Gaussian noise added to function outputs. Default is 0.1.

    Returns:
    tuple: A tuple (x, y) where:
        - x (torch.Tensor): A tensor of shape (N, x_dim), where x_dim is the number of inputs to func.
        - y (torch.Tensor): A tensor of shape (N, 1) containing the noisy function outputs.
    """

    x_dim = len(signature(func).parameters)  # Number of inputs to the function
    x = (range_max - range_min) * torch.rand([N, x_dim]) + range_min
    y = torch.tensor([[func(*x_i)] for x_i in x], dtype=torch.float32)

    # Adding Gaussian noise
    noise = torch.randn(y.shape) * noise_std
    y_noisy = y + noise

    return x, y_noisy

# Define train and test first dataset

x_train, y_train = generate_data(lambda x: 2 * x + np.sin(x) + x * np.sin(x), 240, -2, 2)
plt.scatter(x_train, y_train)
plt.title('Train Dataset')
plt.show()

# We change range_min and range_max here to test its OOD (out-of-distribution) performance

x_test, y_test = generate_data(lambda x: 2 * x + np.sin(x) + x * np.sin(x), 60, -10, 10)
plt.scatter(x_test, y_test)
plt.title('Test Dataset')
plt.show()

"""# EQL

Equation Learner (EQL) is a neural network-based approach to symbolic regression that discovers mathematical expressions directly from data. Unlike traditional deep learning models that treat regression as a black-box approximation, EQL is designed to output interpretable symbolic expressions. EQL uses a special type of neural network where activation functions are not just standard non-linearities (like ReLU or sigmoid) but include mathematical operations such as addition, multiplication, and trigonometric functions (e.g., sin(x), cos(x)).

<p align="center">
  <img style="margin-top: 30px" src="https://camo.githubusercontent.com/f4722b552bd6d4bd3909ff054ebef8bc4a973d9dd93e2ccacd6c77f4e03e3443/68747470733a2f2f692e696d6775722e636f6d2f485a58776656492e706e67" width="1000">
</p>

### Retrieve expressions

This cell is used to retrieve expressions from the network. Do not modify this cell.
"""

# DON'T CHNAGE THIS CELL

"""
Generate a mathematical expression for the symbolic regression get_expression (also known as the EQL network) using SymPy.
This expression can be utilized for pretty-printing in various formats, including human-readable text and LaTeX.
Additionally, SymPy enables algebraic manipulation of the expression.
"""


def apply_activation(W, funcs, n_double=0):
    """Given an (n, m) matrix W and (m) vector of funcs, apply funcs to W.

    Arguments:
        W:  (n, m) matrix
        funcs: list of activation functions (SymPy functions)
        n_double:   Number of activation functions that take in 2 inputs

    Returns:
        SymPy matrix with 1 column that represents the output of applying the activation functions.
    """
    W = sp.Matrix(W)
    if n_double == 0:
        for i in range(W.shape[0]):
            for j in range(W.shape[1]):
                W[i, j] = funcs[j](W[i, j])
    else:
        W_new = W.copy()
        out_size = len(funcs)
        for i in range(W.shape[0]):
            in_j = 0
            out_j = 0
            while out_j < out_size - n_double:
                W_new[i, out_j] = funcs[out_j](W[i, in_j])
                in_j += 1
                out_j += 1
            while out_j < out_size:
                W_new[i, out_j] = funcs[out_j](W[i, in_j], W[i, in_j+1])
                in_j += 2
                out_j += 1
        for i in range(n_double):
            W_new.col_del(-1)
        W = W_new
    return W


def sym_pp(W_list, funcs, var_names, threshold=0.01, n_double=0):
    """Pretty print the hidden layers (not the last layer) of the symbolic regression network

    Arguments:
        W_list: list of weight matrices for the hidden layers
        funcs:  list of lambda functions using sympy. has the same size as W_list[i][j, :]
        var_names: list of strings for names of variables
        threshold: threshold for filtering expression. set to 0 for no filtering.
        n_double:   Number of activation functions that take in 2 inputs

    Returns:
        Simplified sympy expression.
    """
    vars = []
    for var in var_names:
        if isinstance(var, str):
            vars.append(sp.Symbol(var))
        else:
            vars.append(var)
    expr = sp.Matrix(vars).T
    # W_list = np.asarray(W_list)
    for W in W_list:
        W = filter_mat(sp.Matrix(W), threshold=threshold)
        expr = expr * W
        expr = apply_activation(expr, funcs, n_double=n_double)
    # expr = expr * W_list[-1]
    return expr


def last_pp(eq, W):
    """Pretty print the last layer."""
    return eq * filter_mat(sp.Matrix(W))


def count_inputs(funcs):
    i = 0
    for func in funcs:
        if isinstance(func, BaseFunction):
            i += 1
        elif isinstance(func, BaseFunction2):
            i += 2
    return i


def count_double(funcs):
    i = 0
    for func in funcs:
        if isinstance(func, BaseFunction2):
            i += 1
    return i


def get_expression(weights, funcs, var_names, threshold=0.01):
    """Pretty print the entire symbolic regression network.

    Arguments:
        weights: list of weight matrices for the entire network
        funcs:  list of lambda functions using sympy. has the same size as W_list[i][j, :]
        var_names: list of strings for names of variables
        threshold: threshold for filtering expression. set to 0 for no filtering.

    Returns:
        Simplified sympy expression."""
    n_double = count_double(funcs)
    funcs = [func.sp for func in funcs]

    expr = sym_pp(weights[:-1], funcs, var_names, threshold=threshold, n_double=n_double)
    expr = last_pp(expr, weights[-1])
    expr = expr[0, 0]
    return expr


def filter_mat(mat, threshold=0.01):
    """Remove elements of a matrix below a threshold."""
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            if abs(mat[i, j]) < threshold:
                mat[i, j] = 0
    return mat


def filter_expr(expr, threshold=0.01):
    expr_new = sp.Integer(0)
    for arg in expr.args:
        if arg.is_constant() and abs(arg) > threshold:   # hack way to check if it's a number
            expr_new = expr_new + arg
        elif not arg.is_constant() and abs(arg.args[0]) > threshold:
            expr_new = expr_new + arg
    return expr_new


def filter_expr2(expr, threshold=0.01):
    for a in sp.preorder_traversal(expr):
        if isinstance(a, sp.Float) and a < threshold:
            expr = expr.subs(a, 0)
    return expr

"""### Base Functions
These cells contain functions for use in symbolic regression. Each function encapsulates multiple implementations (SymPy, Torch) of a particular operation, allowing them to be used in different contexts. You need to complete the Torch sections.
"""

# Complete TODO parts

"""Functions for use with symbolic regression.

These functions encapsulate multiple implementations (sympy, torch) of a particular function so that the
functions can be used in multiple contexts."""

class BaseFunction:
    """Abstract class for primitive functions"""
    def __init__(self, norm=1):
        self.norm = norm

    def sp(self, x):
        """Sympy implementation"""
        return None

    def torch(self, x):
        """No need for base function"""
        return None

    def name(self, x):
        return str(self.sp)


class Constant(BaseFunction):
    def torch(self, x):
        return torch.ones_like(x)

    def sp(self, x):
        return 1


class Identity(BaseFunction):
    """
    A function class that applies an identity transformation with normalization.

    Attributes:
    norm (float): A normalization factor that scales the input.

    Methods:
    torch(x: torch.Tensor) -> torch.Tensor:
        Applies the identity transformation by dividing the input by the normalization factor.
    """

    def torch(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the identity function with normalization.

        Parameters:
        x (torch.Tensor): The input tensor.

        Returns:
        torch.Tensor: The normalized output tensor.

        """
        # ================ TODO ================
        return x / self.norm
        # ======================================
    def sp(self, x):
        return x / self.norm



class Square(BaseFunction):
    """
    A function class that applies a squared transformation with normalization.

    Methods:
    torch(x: torch.Tensor) -> torch.Tensor:
        Returns the squared value of the input, divided by the normalization factor.
    """

    def torch(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the squared function with normalization.

        Parameters:
        x (torch.Tensor): The input tensor.

        Returns:
        torch.Tensor: The squared output tensor divided by the normalization factor.
        """
        # ================ TODO ================
        return torch.pow(x, 2) / self.norm
        # ======================================


    def sp(self, x):
        return x ** 2 / self.norm


class Pow(BaseFunction):
    """
    A function class that raises the input to a given power and normalizes the result.

    Attributes:
    power (float): The exponent to which the input is raised.

    Methods:
    torch(x: torch.Tensor) -> torch.Tensor:
        Raises the input to the specified power and divides by the normalization factor.
    """

    def __init__(self, power: float, norm: float = 1):
        """
        Initializes the Pow function with a given exponent and normalization factor.

        Parameters:
        power (float): The exponent for the power function.
        norm (float, optional): The normalization factor. Default is 1.
        """

        BaseFunction.__init__(self, norm=norm)
        self.power = power

    def torch(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the power function with normalization.

        Parameters:
        x (torch.Tensor): The input tensor.

        Returns:
        torch.Tensor: The output tensor, where each element is raised to the given power and normalized.
        """
        # ================ TODO ================
        return torch.pow(x, self.power) / self.norm
        # ======================================


    def sp(self, x):
        return x ** self.power / self.norm

class Sin(BaseFunction):
    """
    A function class that applies a sine transformation with frequency scaling and normalization.

    Methods:
    torch(x: torch.Tensor) -> torch.Tensor:
        Applies a sine transformation to the input and divides by the normalization factor.
    """

    def torch(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the sine function with frequency scaling and normalization.

        Parameters:
        x (torch.Tensor): The input tensor.

        Returns:
        torch.Tensor: The sine-transformed tensor divided by the normalization factor.
        """

        # ================ TODO ================
        return torch.sin(x * 4 * np.pi) / self.norm
        # ======================================


    def sp(self, x):
        return sp.sin(x * 2*2*np.pi) / self.norm


class Sigmoid(BaseFunction):
    """
    A function class that applies the sigmoid function with normalization.

    Methods:
    torch(x: torch.Tensor) -> torch.Tensor:
        Applies the sigmoid function and divides by the normalization factor.
    """

    def torch(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the sigmoid function with normalization.

        Parameters:
        x (torch.Tensor): The input tensor.

        Returns:
        torch.Tensor: The sigmoid-transformed tensor divided by the normalization factor.
        """

        # ================ TODO ================
        return torch.sigmoid(20 * x) / self.norm
        # ======================================


    def sp(self, x):
        return 1 / (1 + sp.exp(-20*x)) / self.norm

    def name(self, x):
        return "sigmoid(x)"


class Exp(BaseFunction):
    """
    A function class that applies an exponential transformation with normalization.

    Methods:
    torch(x: torch.Tensor) -> torch.Tensor:
        Applies the exponential function (subtracting 1) and divides by the normalization factor.
    """

    def __init__(self, norm: float = np.e):
        """
        Initializes the Exp function with a normalization factor.

        Parameters:
        norm (float, optional): The normalization factor. Default is Euler's number (e).
        """
        super().__init__(norm)

    def torch(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the modified exponential function with normalization.

        Parameters:
        x (torch.Tensor): The input tensor.

        Returns:
        torch.Tensor: The transformed tensor, where exp(x) - 1 is computed and divided by the normalization factor.
        """

        # ================ TODO ================
        return (torch.exp(x) - 1) / self.norm
        # ======================================

    def sp(self, x):
        return (sp.exp(x) - 1) / self.norm


class Log(BaseFunction):
    """
    A function class that applies the logarithm function with normalization.

    Methods:
    torch(x: torch.Tensor) -> torch.Tensor:
        Applies the logarithm function (on the absolute value of input) and divides by the normalization factor.
    """

    def torch(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the logarithm function with normalization.

        Parameters:
        x (torch.Tensor): The input tensor.

        Returns:
        torch.Tensor: The log-transformed tensor divided by the normalization factor.
        """

        # ================ TODO ================
        return torch.log(torch.abs(x) + 1e-8) / self.norm # Add a small epsilon for numerical stability
        # ======================================

    def sp(self, x):
        return sp.log(sp.Abs(x)) / self.norm


class BaseFunction2:
    """Abstract class for primitive functions with 2 inputs"""
    def __init__(self, norm=1.):
        self.norm = norm

    def sp(self, x, y):
        """Sympy implementation"""
        return None

    def torch(self, x, y):
        return None

    def name(self, x, y):
        return str(self.sp)


class Product(BaseFunction2):
    """
    A function class that computes the product of two inputs with normalization.

    Methods:
    torch(x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        Computes the product of two input tensors and divides by the normalization factor.
    """

    def __init__(self, norm: float = 0.1):
        """
        Initializes the Product function with a normalization factor.

        Parameters:
        norm (float, optional): The normalization factor. Default is 0.1.
        """
        super().__init__(norm=norm)

    def torch(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        """
        Computes the product of two input tensors with normalization.

        Parameters:
        x (torch.Tensor): The first input tensor.
        y (torch.Tensor): The second input tensor.

        Returns:
        torch.Tensor: The element-wise product of x and y, divided by the normalization factor.
        """

        # ================ TODO ================
        return torch.mul(x, y) / self.norm
        # ======================================

    def sp(self, x, y):
        return x * y / self.norm

"""### Model Architecture

In this section, we define the architecture of the symbolic regression neural network using the Equation Learner (EQL) approach. The model is designed to learn mathematical expressions by incorporating activation functions that correspond to primitive mathematical operations.

1. SymbolicLayer: Each layer applies a set of predefined functions (e.g., sin(x), cos(x), x^2, etc.). The weight matrix determines how input features are transformed and combined. Functions are applied either as single-input (f(x)) or double-input (f(x, y)) operations.

2. SymbolicNet: Composed of multiple SymbolicLayer instances. Uses trainable weight matrices to learn meaningful expressions. The final layer outputs a weighted sum without an activation function.
"""

"""Contains the symbolic regression neural network architecture."""
import numpy as np
import torch
import torch.nn as nn

def count_double(funcs):
    return sum(isinstance(f, BaseFunction2) for f in funcs)

def count_inputs(funcs):
    singles = sum(isinstance(f, BaseFunction) for f in funcs)
    doubles = count_double(funcs)
    return singles + 2 * doubles

class SymbolicLayer(nn.Module):
    """Neural network layer for symbolic regression where activation functions correspond to primitive functions.
    Can take multi-input activation functions (like multiplication)"""
    def __init__(self, funcs, initial_weight=None, init_stddev=0.1, in_dim=None):
        """
        funcs: List of activation functions, using utils.functions
        initial_weight: (Optional) Initial value for weight matrix
        variable: Boolean of whether initial_weight is a variable or not
        init_stddev: (Optional) if initial_weight isn't passed in, this is standard deviation of initial weight

        Parameters need to define:

        - self.W: The weight matrix of the layer. It maps the input features to the output functions. If an `initial_weight` is provided, it is used as the initial weight matrix.
                  Otherwise, it is initialized from a normal distribution with mean 0 and standard deviation `init_stddev`.
        """

        # This structure of this network is just a suggested. If you want you can make a different network but it should implement EQL.

        super().__init__()

        self.funcs_cfg = funcs  # keep the original objects (we need them for count_* helpers)
        self.funcs = [f.torch for f in funcs]
        self.n_funcs = len(funcs)
        self.n_double = count_double(funcs)
        self.n_single = self.n_funcs - self.n_double
        # weight matrix requires one column per single‑input op and two per double‑input op
        self.out_dim = self.n_single + 2 * self.n_double


        # Define and initialize the weight matrix `W`.
        # If `initial_weight` is provided, use it; otherwise, initialize with a normal distribution.

        # =================================== TODO ===================================
        if initial_weight is not None:
            W_init = torch.as_tensor(initial_weight, dtype=torch.float32)
        else:
            W_init = torch.randn(in_dim, self.out_dim) * init_stddev
        self.W = nn.Parameter(W_init)
        # ============================================================================

    def forward(self, x):

        """
        Computes the forward pass of the layer.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, in_dim).

        Returns:
            torch.Tensor: Output tensor after applying the symbolic functions.

        Process:
            1. Multiply input `x` with weight matrix `W` to get weighted sum `g`.
            2. Apply the activation functions:
               - Single-input functions take one element from `g`.
               - Two-input functions take two elements from `g` and produce a single output.
            3. Stack all function outputs into a single tensor.
        """
        # =================================== TODO ===================================
        g = x.matmul(self.W)  # shape: (batch, out_dim)
        out = []
        ptr = 0
        # print(f"g: {g.size()}")
        # print(f"funcs: count={self.n_funcs}")
        # [print(f"- func[{i}]: {self.funcs[i]}") for i in range(len(self.funcs))]
        for idx, func in enumerate(self.funcs):
            if idx < self.n_single:  # single‑input op
                out.append(func(g[:, ptr]))
                # print(f"func{idx} input1: {g[:, ptr].size()}")
                # print(f"func{idx} output: {func(g[:, ptr]).size()}")
                ptr += 1
            else:  # double‑input op – consume two columns
                out.append(func(g[:, ptr], g[:, ptr + 1]))
                # print(f"func{idx} input1: {g[:, ptr].size()}")
                # print(f"func{idx} input2: {g[:, ptr + 1].size()}")
                # print(f"func{idx} output: {func(g[:, ptr], g[:, ptr + 1]).size()}")
                ptr += 2
        # [print(f"out[{i}]: {out[i].size()}") for i in range(len(out))]
        return torch.stack(out, dim=1)
        # ============================================================================

    def get_weight(self):
        # don't change this function
        return self.W.cpu().detach().numpy()

    def get_weight_tensor(self):
        # don't change this function
        return self.W.clone()


class SymbolicNet(nn.Module):
    """Symbolic regression network with multiple layers. Produces one output."""
    def __init__(self, symbolic_depth, in_dim=1, funcs=None, initial_weights=None, init_stddev=0.1):
        super(SymbolicNet, self).__init__()

        """
        Initializes the symbolic regression network.

        Parameters:
        symbolic_depth (int): The number of hidden layers in the network.
        funcs (list): A list of functions to be used in each layer of the network.
        initial_weights (list or None): Predefined initial weights for each layer. If None, the network will initialize weights randomly.
        init_stddev (float or list): Standard deviation for weight initialization. If a list, each layer will have its own stddev for initialization.

        Hints:
        The first layer will have 1 input dimension (the data itself), and subsequent layers will have the same number of functions as the depth.
        If predefined weights are provided, initialize layers with those weights. otherwise Initialize the network randomly if no initial weights are provided.
        Don't foget to Initialize the output weight (no activation function applied there).

        **Parametrs to define** :

        - self.depth: The number of hidden layers in the network. It determines how many `SymbolicLayer` instances are stacked in the model.

        - self.hidden_layers: A sequential container (`nn.Sequential`) that stores the hidden layers of the network.
                              Each layer is an instance of `SymbolicLayer`, and they are initialized with the provided  activation functions and weights.

        - self.output_weight: A parameter representing the weight matrix for the final layer, mapping the last hidden  layer's output to a single output value.
                              This weight is either initialized from  `initial_weights` (if provided) or randomly initialized when `initial_weights` is None.
        """

        # =================================== TODO ===================================
        super().__init__()
        self.depth = symbolic_depth
        if funcs is None:
            raise ValueError("funcs list must be provided")
        self.hidden_layers = nn.ModuleList()
        curr_in_dim = in_dim
        for d in range(self.depth):
            iw = None
            if initial_weights is not None and d < len(initial_weights):
                iw = initial_weights[d]
            layer = SymbolicLayer(funcs, in_dim=curr_in_dim, initial_weight=iw, init_stddev=init_stddev)
            self.hidden_layers.append(layer)
            curr_in_dim = layer.n_funcs # what comes out goes into next layer
        # output weight (linear, no bias)
        last_iw = None
        if initial_weights is not None and len(initial_weights) == self.depth + 1:
            last_iw = initial_weights[-1]
        if last_iw is not None:
            out_init = torch.as_tensor(last_iw, dtype=torch.float32)
        else:
            out_init = torch.randn(curr_in_dim, 1) * (init_stddev if not isinstance(init_stddev, list) else init_stddev[-1])
        self.output_weight = nn.Parameter(out_init)
        # ============================================================================


    def forward(self, x):
        """
        Defines the forward pass of the network.

        Parameters:
        input (Tensor): The input tensor to the network.

        Returns:
        Tensor: Final output of the network after passing through all layers
        """
        # =================================== TODO ===================================
        h = x
        for i, layer in enumerate(self.hidden_layers):
            h = layer(h)
        return h.matmul(self.output_weight)
        # ============================================================================


    def get_weights(self):
        """Return list of weight matrices"""
        # First part is iterating over hidden weights. Then append the output weight.
        # Don't change this function
        return [l.get_weight() for l in self.hidden_layers] + [self.output_weight.detach().cpu().numpy()]

    def get_weights_tensor(self):
        """Return list of weight matrices as tensors"""
        # Don't change this function
        return [l.get_weight_tensor() for l in self.hidden_layers] + [self.output_weight.clone()]

"""### Training phase"""

from tqdm.auto import tqdm

def train(
    x_train,  # Tensor: Input training data
    y_train,  # Tensor: Target training data
    activation_funcs,  # List of activation functions for each layer
    in_dim, # input dimension
    n_layers,  # Integer: Number of layers in the symbolic regression network
    learning_rate,  # Float: Learning rate for optimization
    summary_step,  # Integer: Interval for logging training progress
    epochs,  # Integer: Number of training epochs
    device="cuda"  # String: Device to perform training on ("cuda" for GPU, "cpu" otherwise)
):
    """
    This function trains a symbolic regression network using the provided training data.

    1. Initializes a `SymbolicNet` object, which represents the symbolic regression model.
    2. The training loop continues as long as the loss is not NaN. If NaN loss occurs, the training will restart.
    3. Optionally, logging can be done at every `summary_step` epoch to track the loss.
    4. (Optional) You can train the network with the full batch of training data.


    Returns:
    - net: The trained symbolic regression network.


    Notes:
    - Feel free to modify the structure if needed. However, keep in mind that extracting expressions requires access to the model's (SymbolicNet) weights.
    """

    # ======================================= TODO =======================================
    device = "cuda" if (device == "cuda" and torch.cuda.is_available()) else "cpu"
    net = SymbolicNet(n_layers, in_dim=in_dim, funcs=activation_funcs).to(device)
    opt = optim.Adam(net.parameters(), lr=learning_rate, weight_decay=1e-6)
    x_train, y_train = x_train.to(device), y_train.to(device)
    restart_attempts = 0
    while True:
        nan_found = False
        for ep in tqdm(range(epochs), total=epochs):
            opt.zero_grad()
            out = net(x_train)
            loss = F.mse_loss(out, y_train)
            if torch.isnan(loss):
                nan_found = True
                break
            loss.backward()
            opt.step()
            if summary_step and ep % summary_step == 0:
                print(f"Epoch {ep:5d}  Loss {loss.item():.6f}")
        if not nan_found:
            break
        restart_attempts += 1
        if restart_attempts > 5:
            raise RuntimeError("Training repeatedly diverged to NaN. Try smaller lr or different init.")
        print("NaN encountered – restarting training with new random init …")
        net = SymbolicNet(n_layers, in_dim=in_dim, funcs=activation_funcs).to(device)
        opt = optim.Adam(net.parameters(), lr=learning_rate, weight_decay=1e-6)
    return net
    # ====================================================================================


def test(net, x_test, y_test, device="cuda"):
    """
    This function tests a symbolic regression network using the provided test data.

    Parameters:
    - net: The trained symbolic regression network (instance of SymbolicNet).
    - x_test: Tensor, the input test data.
    - y_test: Tensor, the target test data.
    - device: String, the device where the test will occur (default is "cuda" for GPU).

    Returns:
    - test_loss: test loss value.
    """
    device = "cuda" if (device == "cuda" and torch.cuda.is_available()) else "cpu"
    x_test, y_test = x_test.to(device), y_test.to(device)
    with torch.no_grad():
        pred = net(x_test)
        loss = F.mse_loss(pred, y_test)
    return float(loss.cpu())

# Don't change this cell

# Define the function that evaluates the expression
def symbolic_function(expr_str, x):
    return eval(expr_str, {"x_1": x, "x1": x, "np": np, "sin": np.sin, "cos": np.cos, "exp": np.exp})

# Function to plot the symbolic regression output and test dataset
def plot_symbolic(x_test, y_test, expr_str):
    x_values = np.linspace(-10, 10, 50)
    y_values = np.array([symbolic_function(expr_str, x) for x in x_values])

    plt.figure(figsize=(10, 5))
    plt.plot(x_values, y_values, label="Symbolic Regression Output", color='b')
    plt.scatter(x_test, y_test, label="Test Dataset", color='r', s=5)
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title("Best results of Symbolic Regression")
    plt.legend()
    plt.grid(True)
    plt.show()

def find_expression(net, x_dim):
  with torch.no_grad():
      weights = net.get_weights()
      expr_str = get_expression(weights, activation_funcs, var_names[:x_dim])
      return expr_str


def run(x_train, x_test, y_train, y_test, activation_funcs, n_layers, learning_rate, summary_step, epochs, trials = 10):
    """
    This function runs the training and testing process for multiple trials.

    The function performs the following steps:
    1. **Training and Testing**: The symbolic regression network is trained and tested for a specified number of trials (default is 10). In each trial:
        - A new model is initialized and trained on the provided training data (`x_train`, `y_train`).
        - The model is then evaluated on the test data (`x_test`, `y_test`) to calculate the test loss (Mean Squared Error).
        - The corresponding symbolic expression is extracted using the `find_expression` function.

    2. **Trial Comparison**: After running all the trials, the best model is selected based on the lowest test loss. This ensures that the model with the best generalization performance is chosen.

    3. **Result Plotting**: The symbolic expression corresponding to the model with the lowest test loss is plotted using the `plot_symbolic` function. The expression is processed to ensure compatibility with NumPy functions (e.g., replacing `exp` with `np.exp` and `sin` with `np.sin`).


    Parameters:
    - No parameters; the function assumes `x_train`, `x_test`, `y_train`, and `y_test` are already defined globally or passed externally.

    Returns:
    - None: The function performs training and testing, logs results, and plots the best model's symbolic expression.
    """

    # ============================================= TODO =============================================
    test_losses = []
    expressions = []
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Running on device: {device}")

    for i in range(trials):
        print(f"\n----- Trial {i+1}/{trials} -----")
        # Train model
        net = train(x_train, y_train, activation_funcs, x_train.shape[1], n_layers, learning_rate, summary_step, epochs, device=device)

        # Test model
        test_loss = test(net, x_test, y_test, device=device)
        test_losses.append(test_loss)
        print(f"Trial {i+1} Test Loss: {test_loss:.4f}")

        # Find expression
        expr = find_expression(net, x_train.shape[1])
        expressions.append(expr)
        print(f"Trial {i+1} Expression: {expr}")
    # ================================================================================================


    best_index = np.argmin(np.array(test_losses))
    return str(expressions[best_index])

activation_funcs = [
    *[Constant()] * 2,
    *[Identity()] * 4,
    *[Square()] * 4,
    *[Sin()] * 2,
    *[Exp()] * 2,
    *[Sigmoid()] * 2,
    *[Product()] * 2,
]


var_names = ["x_1", "x_2"]      # This is the name of vars to show at the end.

n_layers = 2               # TODO: Number of hidden layers
reg_weight = 1e-4          # TODO: Regularization weight
learning_rate = 1e-2       # TODO: Learning rate
summary_step = 10        # TODO: Number of steps between logging summaries
epochs = 1000             # TODO: Number of epochs
trials = 5                 # TODO: Number of trials. note that it should be at least 5.

best_expr = run(x_train, x_test, y_train, y_test, activation_funcs, n_layers, learning_rate, summary_step, epochs, trials)
plot_symbolic(x_test, y_test, best_expr.replace("exp", "np.exp").replace("sin", "np.sin"))

# Now, change the activation functions and the number of layers (n_layers) to observe the effect on the outputs.

for n_layers in range(3, 5):
    best_expr = run(x_train, x_test, y_train, y_test, activation_funcs, n_layers, learning_rate, summary_step, epochs, trials)
    plot_symbolic(x_test, y_test, best_expr.replace("exp", "np.exp").replace("sin", "np.sin"))

"""We were previously working with the first dataset. Now, evaluate the model on the second dataset and extract the corresponding expression."""

# TODO: Find expression for second dataset.

# =================================== TODO ===================================

# ============================================================================

"""### Bonus

We know that in the first and second dataset, the expression is simple and contains only one or at most two terms. However, as you can see, the expressions here are quite long. Now, think about what adjustments you can make to simplify them and reduce their length.
"""

# TODO

